; Arduino Nano ATmega328P — IC Tester
; For new bootloader variant change board to: nanoatmega328new
[env:nano]
platform        = atmelavr
board           = nanoatmega328
framework       = arduino
monitor_speed   = 115200
lib_deps        =
    adafruit/Adafruit INA219@^1.2.0
